### ISSUE TITLE
[Bug] Electron process becomes unresponsive to SIGINT

### ISSUE THREAD

**Issue by Androbin** [berstend/puppeteer-extra#467]
**Describe the bug**

Sending a SIGINT signal to the Electron process does not kill the process.

**Code Snippet**

`package.json`
```json
{
  "name": "test",
  "main": "main.js",
  "scripts": {
    "postinstall": "electron-builder install-app-deps",
    "start": "electron ."
  },
  "dependencies": {
    "puppeteer": "^8.0.0",
    "puppeteer-extra": "^3.1.16",
    "puppeteer-extra-plugin-stealth": "^2.7.6"
  },
  "devDependencies": {
    "electron": "^12.0.2",
    "electron-builder": "^22.10.5"
  }
}

```

`main.js`
```js
const puppeteer = require('puppeteer-extra')
const StealthPlugin = require('puppeteer-extra-plugin-stealth')
puppeteer.use(StealthPlugin())
puppeteer.launch().then(browser => browser.close());
```

**Versions**

```yaml
  System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 227.82 MB / 15.36 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.20.1 - ~/.nvm/versions/node/v12.20.1/bin/node
    npm: 7.6.3 - ~/.nvm/versions/node/v12.20.1/bin/npm
  npmPackages:
    puppeteer: ^8.0.0 => 8.0.0 
    puppeteer-extra: ^3.1.18 => 3.1.18 
    puppeteer-extra-plugin-stealth: ^2.7.6 => 2.7.6
```
