### ISSUE TITLE
[Bug] Plugin incorrectly listed as "missing" when using Yarn PnP and workspaces

### ISSUE THREAD

**Issue by kevinji** [berstend/puppeteer-extra#587]
**Describe the bug**

When using Yarn PnP and workspaces, the code for missing plugins incorrectly appears, even when the package is installed correctly.

Here's an example of the error when using `puppeteer-extra-plugin-stealth`:
```
❯ yarn run start

          A plugin listed 'puppeteer-extra-plugin-stealth/evasions/chrome.app' as dependency,
          which is currently missing. Please install it:

          yarn add puppeteer-extra-plugin-stealth

          Note: You don't need to require the plugin yourself,
          unless you want to modify it's default settings.

/Users/kevinji/Documents/GitHub/puppeteer-extra-yarn-bug/.pnp.cjs:10660
    if (typeof firstError.pnpCode === `string`) Error.captureStackTrace(firstError);
                                                      ^

Error: puppeteer-extra tried to access puppeteer-extra-plugin-stealth, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: puppeteer-extra-plugin-stealth (via "puppeteer-extra-plugin-stealth/evasions/chrome.app")
Required by: puppeteer-extra@virtual:8667c994bb5c18676842d0798db4e99508a3bad0c005d5f7f6d2db3aa9273f585d3ecece253f3ffde3c60648dcd2dac31c940d5aa5422f5845c720bc33f6de97#npm:3.2.3 (via /Users/kevinji/Documents/GitHub/puppeteer-extra-yarn-bug/.yarn/__virtual__/puppeteer-extra-virtual-2f57cc8af1/0/cache/puppeteer-extra-npm-3.2.3-8b4bccf823-a49f4b212f.zip/node_modules/puppeteer-extra/dist/)

Require stack:
- /Users/kevinji/Documents/GitHub/puppeteer-extra-yarn-bug/.yarn/__virtual__/puppeteer-extra-virtual-2f57cc8af1/0/cache/puppeteer-extra-npm-3.2.3-8b4bccf823-a49f4b212f.zip/node_modules/puppeteer-extra/dist/index.cjs.js
- /Users/kevinji/Documents/GitHub/puppeteer-extra-yarn-bug/bug-test/index.js
    at Function.external_module_.Module._resolveFilename (/Users/kevinji/Documents/GitHub/puppeteer-extra-yarn-bug/.pnp.cjs:10660:55)
    at Function.external_module_.Module._load (/Users/kevinji/Documents/GitHub/puppeteer-extra-yarn-bug/.pnp.cjs:10459:48)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at PuppeteerExtra.resolvePluginDependencies (/Users/kevinji/Documents/GitHub/puppeteer-extra-yarn-bug/.yarn/__virtual__/puppeteer-extra-virtual-2f57cc8af1/0/cache/puppeteer-extra-npm-3.2.3-8b4bccf823-a49f4b212f.zip/node_modules/puppeteer-extra/dist/index.cjs.js:300:23)
    at PuppeteerExtra.launch (/Users/kevinji/Documents/GitHub/puppeteer-extra-yarn-bug/.yarn/__virtual__/puppeteer-extra-virtual-2f57cc8af1/0/cache/puppeteer-extra-npm-3.2.3-8b4bccf823-a49f4b212f.zip/node_modules/puppeteer-extra/dist/index.cjs.js:118:14)
    at /Users/kevinji/Documents/GitHub/puppeteer-extra-yarn-bug/bug-test/index.js:7:35
    at Object.<anonymous> (/Users/kevinji/Documents/GitHub/puppeteer-extra-yarn-bug/bug-test/index.js:13:3)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
```

**Code Snippet**

A simplified repro of the issue can be found at https://github.com/kevinji/puppeteer-extra-yarn-bug.

**Versions**

 System:
    OS: macOS 11.6.1
    CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
    Memory: 332.45 MB / 16.00 GB
    Shell: 5.8 - /usr/local/bin/zsh
  Binaries:
    Node: 17.0.1 - /private/var/folders/db/9pdwfph118q9cwsdhybqz9t80000gn/T/xfs-e98176d0/node
    Yarn: 3.1.0 - /private/var/folders/db/9pdwfph118q9cwsdhybqz9t80000gn/T/xfs-e98176d0/yarn
    npm: 8.1.2 - /usr/local/bin/npm

**Comment by kevinji** [comment]
Update: I resolved the issue locally by declaring all the puppeteer dependencies to be peerDependencies of each other in `.yarnrc.yml`:

```
packageExtensions:
  "puppeteer-extra@*":
    peerDependencies:
      puppeteer-extra-plugin-stealth: "*"
      puppeteer-extra-plugin-user-data-dir: "*"
      puppeteer-extra-plugin-user-preferences: "*"
  "puppeteer-extra-plugin-stealth@*":
    peerDependencies:
      puppeteer-extra: "*"
  "puppeteer-extra-plugin-user-data-dir@*":
    peerDependencies:
      puppeteer-extra: "*"
  "puppeteer-extra-plugin-user-preferences@*":
    peerDependencies:
      puppeteer-extra: "*"
```

I think these should belong in the `package.json` for the various packages though.

**Comment by alamothe** [comment]
Looks like the current `puppeteer-extra` plugin system is completely busted in Yarn PNP.

**Comment by berstend** [comment]
<img width="826" alt="image" src="https://user-images.githubusercontent.com/1368633/177132351-cba125eb-249c-49ea-9ce9-37f6b244a319.png">

**Comment by kevinji** [comment]
Sounds good, going to close.

**Comment by bryanph** [comment]
This still doesn't work because of this line: https://github.com/berstend/puppeteer-extra/blob/523b2efe7dc000536ef6bd608810d4e01e206504/packages/puppeteer-extra/src/index.ts#L364

It tries to require from within `puppeteer-extra` which pnp does not like.

The only way to get around this right now seems to be to install literally every puppeteer-extra plugin. Not so nice :(

**Comment by damienbry** [comment]
Thanks @bryanph for the workaround, works for me 🙌 

I'm using yarn PnP with workspaces as a monorepo, I had to :
- I'm using the puppeteer & stealth only in one workspace, add to install the stealth dependencies (puppeteer-extra-plugin-user-preferences, puppeteer-extra-plugin-user-data-dir) in the targeted workspace
- add this to the root .yarnrc.yml and **not the one** in the targeted workspace (this was my mistake)

```yml
packageExtensions:
  "puppeteer-extra@*":
    dependencies:
      puppeteer-extra-plugin-user-preferences: "*"
      puppeteer-extra-plugin-user-data-dir: "*"
    peerDependencies:
      puppeteer-extra-plugin-stealth: "*"
```
